apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: prod-jenkins
spec:
  jenkinsAPISettings: 
    properties:
      authorizationStrategy:
        type: string
    type: object
  service:
    type: LoadBalancer
    port: 8080
  master:
    disableCSRFProtection: true
    basePlugins:
    - name: kubernetes
      version: "1.25.2"
    - name: workflow-job
      version: "2.39"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.2.2"
    - name: job-dsl
      version: "1.77"
    - name: configuration-as-code
      version: "1.38"
    - name: kubernetes-credentials-provider
      version: "0.13"
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
      securityContext:
        runAsUser: 1000
  seedJobs:
  - id: jenkins-operator
    targets: "cicd/jobs/*.jenkins"
    description: "Jenkins Operator Example Repository"
    repositoryBranch: jenkins_operator
    repositoryUrl: https://github.com/pavan-kumar-99/medium-manifests.git